Featured games
XsidX/xbox-bethesda-games-showcase pull request #2
Opened 2022-06-23 13:11 UTC by XsidX

For this project, I have:
-Created a two-page website with a home and about page.
-Created a side navigation menu for smaller screens.
-Created a dynamically generated featured games section from a **featuredGames** object.
-Added a **more** button on the featured games section that expands to display more games from the featured games object.
-The home page has five sections: _hero section, program section, featured games section, partner section and a footer._
-The about page has four sections:  _hero section, past showcases section, partner section and the footer._

2022-06-23 14:43 UTC, Ginohmk requested changes
Hi @XsidX , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!



## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You code reviewer:
- `@kanu mike chibundu`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-06-23 14:43 UTC, koachcode commented on README.md
- You have done a good job on this project, however, please provide a recorded video (Loom preferable ) with the following.(You can add the link to the video on your PR summary )
  - The maximum length of the video is 5 minutes.
  - The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
  - The video contains a demo of the project, showing the pages in different screen sizes.
  - The video contains a highlight about a piece of the code the student finds interesting or is proud of making.

- [Optional] I will suggest you explicitly state out the steps in cloning the repo and going to the directory. so it looks more descriptive.

2022-06-24 09:05 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @XsidX 

Your project is complete! Great job for making the requested changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Validations correctly implemented
- project looks good
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

- [ optional] since the previous reviewer didn't mention, you omitted the first nav bar with the social icons, language and signout, kindly add that to make it more interactive
- [ optional] kindly make the nav links work so they can take you to their respective sections
- [optional] on the mobile version you can send the logo to the corner instead of centered
- [optional] please make the red line under your partner and program section centered

![tufoin](https://media.giphy.com/media/b5L1Lt3k4hGNDZWVIw/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 09:05 UTC, tufoinnkuo10 commented on README.md
> +> In this project, I build an online webiste for the Xbox & Bethesda games showcase.
- [ optional] since the previous reviewer didn't mention it is marked optional. kindly add a good description of what you did in this project so from the readme someone will have a full idea of it

2022-06-24 09:08 UTC, merged